// src/components/toolbar/Toolbar.tsx
import React, { useEffect, useRef, useState } from 'react';
import type { Grid, GridSet, SavedGrid, WordDefinitionData } from '../../models/types';
import './Toolbar.css';

export interface AppearanceSettings {
    blackCellColor: string;
    cellBackgroundColor: string;
    arrowColor: string;
    letterColor: string;
    definitionTextColor: string;
    borderColor: string;
    separatorColor: string;
    gridFont: string;
    definitionFont: string;
}

interface ToolbarProps {
    onResize: (width: number, height: number) => void;
    currentGrid?: Grid;
    definitions: Record<string, WordDefinitionData>;
    onInputFocus: (isFocused: boolean) => void;
    appearance: AppearanceSettings;
    onAppearanceChange: (changes: Partial<AppearanceSettings>) => void;
    savedGrids: SavedGrid[];
    onSavedGridsChange: (grids: SavedGrid[]) => void;
    onGridLoad: (grid: Grid, definitions?: Record<string, WordDefinitionData>) => void;
    gridSets: GridSet[];
    currentSetName: string;
    onSetNameChange: (name: string) => void;
    onNewSet: () => void;
    onExportSet: () => void;
    onImportSetData: (content: string) => void;
    onExportGridPdf: () => void;
    onExportSetPdf: () => void;
    onSelectSet: (id: string) => void;
    currentSetId: string | null;
}

export const Toolbar: React.FC<ToolbarProps> = ({
    onResize,
    currentGrid,
    definitions,
    onInputFocus,
    appearance,
    onAppearanceChange,
    savedGrids,
    onSavedGridsChange,
    onGridLoad,
    gridSets,
    currentSetName,
    onSetNameChange,
    onNewSet,
    onExportSet,
    onImportSetData,
    onExportGridPdf,
    onExportSetPdf,
    onSelectSet,
    currentSetId
}) => {
    const [activePanel, setActivePanel] = useState<'info' | 'appearance' | null>(null);
    const [gridName, setGridName] = useState(currentGrid?.name || '');
    const [showLoadDropdown, setShowLoadDropdown] = useState(false);
    const [dimensions, setDimensions] = useState({
        width: currentGrid?.size.width || 15,
        height: currentGrid?.size.height || 15
    });
    const [gridFontCustom, setGridFontCustom] = useState(appearance.gridFont);
    const [definitionFontCustom, setDefinitionFontCustom] = useState(appearance.definitionFont);
    const [showSetDropdown, setShowSetDropdown] = useState(false);
    type ColorKey =
        | 'blackCellColor'
        | 'cellBackgroundColor'
        | 'arrowColor'
        | 'letterColor'
        | 'definitionTextColor'
        | 'borderColor'
        | 'separatorColor';
    const [colorDrafts, setColorDrafts] = useState<Record<ColorKey, string>>({
        blackCellColor: appearance.blackCellColor,
        cellBackgroundColor: appearance.cellBackgroundColor,
        arrowColor: appearance.arrowColor,
        letterColor: appearance.letterColor,
        definitionTextColor: appearance.definitionTextColor,
        borderColor: appearance.borderColor,
        separatorColor: appearance.separatorColor
    });
    const gridFontFileInput = useRef<HTMLInputElement | null>(null);
    const definitionFontFileInput = useRef<HTMLInputElement | null>(null);
    const setFileInput = useRef<HTMLInputElement | null>(null);

    useEffect(() => {
        setGridName(currentGrid?.name || '');
    }, [currentGrid]);

    useEffect(() => {
        setDimensions({
            width: currentGrid?.size.width || 15,
            height: currentGrid?.size.height || 15
        });
    }, [currentGrid]);

    useEffect(() => {
        setColorDrafts({
            blackCellColor: appearance.blackCellColor,
            cellBackgroundColor: appearance.cellBackgroundColor,
            arrowColor: appearance.arrowColor,
            letterColor: appearance.letterColor,
            definitionTextColor: appearance.definitionTextColor,
            borderColor: appearance.borderColor,
            separatorColor: appearance.separatorColor
        });
        setGridFontCustom(appearance.gridFont);
        setDefinitionFontCustom(appearance.definitionFont);
    }, [appearance]);

    const handleSave = () => {
        if (!gridName.trim() || !currentGrid) return;
        const baseName = gridName.trim();
        const existingIndex = savedGrids.findIndex((g) => g.name === baseName);
        const newSavedGrid: SavedGrid = {
            id: Date.now().toString(),
            name: baseName,
            timestamp: Date.now(),
            grid: {
                ...currentGrid,
                name: baseName
            },
            definitions
        };

        if (existingIndex >= 0) {
            const replace = window.confirm(
                'Une grille porte déjà ce nom. OK pour la remplacer, Annuler pour créer une copie.'
            );

            if (replace) {
                const updatedGrids = savedGrids.map((grid, index) =>
                    index === existingIndex
                        ? { ...newSavedGrid, id: grid.id, timestamp: Date.now() }
                        : grid
                );
                onSavedGridsChange(updatedGrids);
                return;
            }

            let copyIndex = 1;
            let copyName = `${baseName} (copie)`;
            const existingNames = new Set(savedGrids.map((g) => g.name));
            while (existingNames.has(copyName)) {
                copyIndex += 1;
                copyName = `${baseName} (copie ${copyIndex})`;
            }

            onSavedGridsChange([
                ...savedGrids,
                { ...newSavedGrid, name: copyName, grid: { ...newSavedGrid.grid, name: copyName } }
            ]);
            setGridName(copyName);
            return;
        }

        onSavedGridsChange([...savedGrids, newSavedGrid]);
    };

    const handleLoad = (savedGrid: SavedGrid) => {
        if (window.confirm(`Charger la grille "${savedGrid.name}" ?`)) {
            onGridLoad(savedGrid.grid, savedGrid.definitions);
            setShowLoadDropdown(false);
        }
    };

    const handleDelete = (id: string, event: React.MouseEvent) => {
        event.preventDefault();
        event.stopPropagation();

        if (!window.confirm('Êtes-vous sûr de vouloir supprimer cette grille ?')) return;

        const updatedGrids = savedGrids.filter(g => g.id !== id);
        onSavedGridsChange(updatedGrids);
    };

    const handleResize = () => {
        onResize(dimensions.width, dimensions.height);
        setActivePanel(null);
    };

    const handleSetFile = (file?: File | null) => {
        if (!file) return;
        const reader = new FileReader();
        reader.onload = (event) => {
            const content = event.target?.result;
            if (typeof content === 'string') {
                onImportSetData(content);
            }
        };
        reader.readAsText(file);
    };

    const colorFields: { key: ColorKey; label: string }[] = [
        { key: 'blackCellColor', label: 'Couleur des cases noires' },
        { key: 'cellBackgroundColor', label: 'Couleur des cases blanches' },
        { key: 'arrowColor', label: 'Couleur des flèches' },
        { key: 'letterColor', label: 'Couleur des lettres (grille)' },
        { key: 'definitionTextColor', label: 'Couleur des définitions' },
        { key: 'borderColor', label: 'Couleur des bordures de cases' },
        { key: 'separatorColor', label: 'Couleur de la barre de séparation' }
    ];

    const fontOptions = [
        { label: 'Charger une police…', value: 'custom' },
        { label: 'Inter', value: "'Inter', 'Segoe UI', system-ui, sans-serif" },
        { label: 'Arial', value: "Arial, 'Helvetica Neue', sans-serif" },
        { label: 'Roboto', value: "'Roboto', 'Segoe UI', system-ui, sans-serif" },
        { label: 'Lato', value: "'Lato', 'Segoe UI', system-ui, sans-serif" },
        { label: 'Open Sans', value: "'Open Sans', 'Segoe UI', system-ui, sans-serif" },
        { label: 'Montserrat', value: "'Montserrat', 'Segoe UI', system-ui, sans-serif" },
        { label: 'Georgia', value: "Georgia, 'Times New Roman', serif" },
        { label: 'Courier New', value: "'Courier New', monospace" }
    ];

    const normalizeHex = (value: string): string | null => {
        const trimmed = value.trim();
        if (/^#([0-9a-fA-F]{3})$/.test(trimmed)) {
            const [, rgb] = trimmed.match(/^#([0-9a-fA-F]{3})$/) || [];
            if (!rgb) return null;
            return `#${rgb[0]}${rgb[0]}${rgb[1]}${rgb[1]}${rgb[2]}${rgb[2]}`.toLowerCase();
        }
        if (/^#([0-9a-fA-F]{6})$/.test(trimmed)) return trimmed.toLowerCase();
        return null;
    };

    const isValidColor = (value: string) => {
        return (
            normalizeHex(value) !== null ||
            /^rgb(a)?\(/i.test(value.trim()) ||
            /^hsl(a)?\(/i.test(value.trim())
        );
    };

    const sanitizeColor = (value: string, fallback: string) => {
        const normalized = normalizeHex(value);
        if (normalized) return normalized;
        const trimmed = value.trim();
        if (isValidColor(trimmed)) return trimmed;
        return fallback;
    };

    const commitColor = (key: ColorKey, value: string) => {
        const sanitized = sanitizeColor(value, appearance[key]);
        setColorDrafts((prev) => ({ ...prev, [key]: sanitized }));
        if (sanitized !== appearance[key]) {
            onAppearanceChange({ [key]: sanitized });
        }
    };

    const resolveColorValue = (key: ColorKey) =>
        normalizeHex(colorDrafts[key]) ?? normalizeHex(appearance[key]) ?? '#000000';

    const applyFontChange = (key: 'gridFont' | 'definitionFont', value: string) => {
        const nextValue = value.trim() || appearance[key];
        onAppearanceChange({ [key]: nextValue });
    };

    const selectedFontValue = (current: string) => {
        const match = fontOptions.find((opt) => opt.value === current);
        return match ? match.value : 'custom';
    };

    const loadFontFile = async (file: File, target: 'grid' | 'definition') => {
        try {
            const fontName = file.name.replace(/\.[^/.]+$/, '') || 'CustomFont';
            const fontData = await file.arrayBuffer();
            const fontFace = new FontFace(fontName, fontData);
            await fontFace.load();
            (document as Document).fonts.add(fontFace);

            const fontValue = `'${fontName}'`;
            if (target === 'grid') {
                setGridFontCustom(fontValue);
                applyFontChange('gridFont', fontValue);
            } else {
                setDefinitionFontCustom(fontValue);
                applyFontChange('definitionFont', fontValue);
            }
        } catch (error) {
            console.error('Erreur lors du chargement de la police :', error);
            window.alert('Impossible de charger cette police. Merci de réessayer.');
        }
    };

    const triggerFontUpload = (target: 'grid' | 'definition') => {
        const input = target === 'grid' ? gridFontFileInput.current : definitionFontFileInput.current;
        input?.click();
    };

    return (
        <div className="toolbar-container">
            <div className="toolbar-buttons">
                {['info', 'appearance'].map((panel) => (
                    <button
                        key={panel}
                        className={`tool-button ${activePanel === panel ? 'active' : ''}`}
                        onClick={() =>
                            setActivePanel(
                                activePanel === panel ? null : (panel as 'info' | 'appearance')
                            )
                        }
                    >
                        {panel === 'info'
                            ? 'Infos'
                            : 'Apparence'}
                    </button>
                ))}
            </div>
            <div className="toolbar-status">
                <span className="status-item">Set : {currentSetName || 'Nouveau set'}</span>
                <span className="status-item">Grille : {gridName || 'Sans nom'}</span>
            </div>

            {activePanel === 'info' && (
                <div className="tool-content">
                    <div className="tool-panel info-panel">
                        <div className="set-column">
                            <label className="input-label">Set de grilles</label>
                            <input
                                type="text"
                                className="grid-name-input"
                                placeholder="Nom du set"
                                value={currentSetName}
                                onChange={(e) => onSetNameChange(e.target.value)}
                                onFocus={() => onInputFocus(true)}
                                onBlur={() => onInputFocus(false)}
                            />
                            <div className="action-group">
                                <button className="action-button" type="button" onClick={onExportSet}>
                                    Exporter le set
                                </button>
                                <button className="action-button" type="button" onClick={onExportSetPdf}>
                                    Exporter le set (PDF)
                                </button>
                                <button className="tool-button" type="button" onClick={onNewSet}>
                                    Nouveau set de grille
                                </button>
                                <div className="load-dropdown">
                                    <button
                                        className="tool-button"
                                        onClick={() => setShowSetDropdown(!showSetDropdown)}
                                        type="button"
                                    >
                                        Charger un set ▼
                                    </button>
                                    {showSetDropdown && (
                                        <div className="dropdown-content">
                                            <button
                                                className="tool-button full-width"
                                                type="button"
                                                onClick={() => {
                                                    setShowSetDropdown(false);
                                                    setFileInput.current?.click();
                                                }}
                                            >
                                                Importer un set local
                                            </button>
                                            {gridSets.length > 0 ? (
                                                gridSets.map((set) => (
                                                    <div
                                                        key={set.id}
                                                        className={`saved-grid-item ${set.id === currentSetId ? 'active' : ''}`}
                                                        onClick={() => {
                                                            onSelectSet(set.id);
                                                            setShowSetDropdown(false);
                                                        }}
                                                    >
                                                        <div>
                                                            <div>{set.name}</div>
                                                            <small>{set.grids.length} grilles</small>
                                                        </div>
                                                    </div>
                                                ))
                                            ) : (
                                                <div className="no-grids">Aucun set enregistré</div>
                                            )}
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>

                        <div className="grid-column">
                            <label className="input-label">Grille active</label>
                            <input
                                type="text"
                                className="grid-name-input"
                                placeholder="Nom de la grille"
                                value={gridName}
                                onChange={(e) => setGridName(e.target.value)}
                                onFocus={() => onInputFocus(true)}
                                onBlur={() => onInputFocus(false)}
                            />
                            <div className="action-group">
                                <button className="action-button" onClick={handleSave}>
                                    Sauvegarder
                                </button>
                                <div className="load-dropdown">
                                    <button
                                        className="action-button"
                                        onClick={() => setShowLoadDropdown(!showLoadDropdown)}
                                    >
                                        Charger ▼
                                    </button>
                                    {showLoadDropdown && (
                                        <div className="dropdown-content">
                                            {savedGrids.length > 0 ? (
                                                savedGrids.map((savedGrid) => (
                                                    <div
                                                        key={savedGrid.id}
                                                        className="saved-grid-item"
                                                        onClick={() => handleLoad(savedGrid)}
                                                    >
                                                        <div>
                                                            <div>{savedGrid.name}</div>
                                                            <small>
                                                                {new Date(savedGrid.timestamp).toLocaleDateString()}
                                                            </small>
                                                        </div>
                                                        <button
                                                            onClick={(e) => handleDelete(savedGrid.id, e)}
                                                            className="tool-button"
                                                            aria-label="Supprimer"
                                                        >
                                                            ×
                                                        </button>
                                                    </div>
                                                ))
                                            ) : (
                                                <div className="no-grids">
                                                    Aucune grille sauvegardée
                                                </div>
                                            )}
                                        </div>
                                    )}
                                </div>
                                <button className="action-button" type="button" onClick={onExportGridPdf}>
                                    Exporter la grille (PDF)
                                </button>
                            </div>

                            <label className="input-label">Redimensionner</label>
                            <div className="resize-controls">
                                <input
                                    type="number"
                                    className="size-input"
                                    value={dimensions.width}
                                    onChange={(e) => setDimensions({ ...dimensions, width: parseInt(e.target.value) || 15 })}
                                    min="5"
                                    max="25"
                                />
                                <span>×</span>
                                <input
                                    type="number"
                                    className="size-input"
                                    value={dimensions.height}
                                    onChange={(e) => setDimensions({ ...dimensions, height: parseInt(e.target.value) || 15 })}
                                    min="5"
                                    max="25"
                                />
                                <button className="tool-button" onClick={handleResize}>
                                    Appliquer sans effacer
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {activePanel === 'appearance' && (
                <div className="tool-content">
                    <div className="tool-panel appearance-panel">
                        {colorFields.map(({ key, label }) => (
                            <div key={key} className="color-field">
                                <label>{label}</label>
                                <div className="color-inputs">
                                    <input
                                        type="color"
                                        value={resolveColorValue(key)}
                                        onChange={(e) => commitColor(key, e.target.value)}
                                        onFocus={() => onInputFocus(true)}
                                        onBlur={() => onInputFocus(false)}
                                        aria-label={label}
                                    />
                                    <input
                                        type="text"
                                        value={colorDrafts[key]}
                                        onChange={(e) =>
                                            setColorDrafts((prev) => ({ ...prev, [key]: e.target.value }))
                                        }
                                        onFocus={() => onInputFocus(true)}
                                        onBlur={() => {
                                            commitColor(key, colorDrafts[key]);
                                            onInputFocus(false);
                                        }}
                                        className="color-text-input"
                                        placeholder="#000000 ou rgb()"
                                    />
                                </div>
                            </div>
                        ))}

                        <div className="font-field">
                            <label>Police de la grille</label>
                            <select
                                className="font-select"
                                value={selectedFontValue(appearance.gridFont)}
                                onChange={(e) => {
                                    const value = e.target.value;
                                    if (value === 'custom') {
                                        triggerFontUpload('grid');
                                    } else {
                                        applyFontChange('gridFont', value);
                                    }
                                }}
                                onFocus={() => onInputFocus(true)}
                                onBlur={() => onInputFocus(false)}
                            >
                                {fontOptions.map((option) => (
                                    <option key={option.value} value={option.value}>
                                        {option.label}
                                    </option>
                                ))}
                            </select>
                            {selectedFontValue(appearance.gridFont) === 'custom' && (
                                <div className="custom-font-row">
                                    <input
                                        type="text"
                                        value={gridFontCustom}
                                        onChange={(e) => {
                                            setGridFontCustom(e.target.value);
                                            applyFontChange('gridFont', e.target.value);
                                        }}
                                        onFocus={() => onInputFocus(true)}
                                        onBlur={() => onInputFocus(false)}
                                        className="color-text-input"
                                        placeholder="Ex: Inter, Arial, sans-serif"
                                    />
                                    <button
                                        type="button"
                                        className="tool-button"
                                        onClick={() => triggerFontUpload('grid')}
                                    >
                                        Charger une police
                                    </button>
                                </div>
                            )}
                        </div>

                        <div className="font-field">
                            <label>Police des définitions</label>
                            <select
                                className="font-select"
                                value={selectedFontValue(appearance.definitionFont)}
                                onChange={(e) => {
                                    const value = e.target.value;
                                    if (value === 'custom') {
                                        triggerFontUpload('definition');
                                    } else {
                                        applyFontChange('definitionFont', value);
                                    }
                                }}
                                onFocus={() => onInputFocus(true)}
                                onBlur={() => onInputFocus(false)}
                            >
                                {fontOptions.map((option) => (
                                    <option key={option.value} value={option.value}>
                                        {option.label}
                                    </option>
                                ))}
                            </select>
                            {selectedFontValue(appearance.definitionFont) === 'custom' && (
                                <div className="custom-font-row">
                                    <input
                                        type="text"
                                        value={definitionFontCustom}
                                        onChange={(e) => {
                                            setDefinitionFontCustom(e.target.value);
                                            applyFontChange('definitionFont', e.target.value);
                                        }}
                                        onFocus={() => onInputFocus(true)}
                                        onBlur={() => onInputFocus(false)}
                                        className="color-text-input"
                                        placeholder="Ex: Inter, Georgia"
                                    />
                                    <button
                                        type="button"
                                        className="tool-button"
                                        onClick={() => triggerFontUpload('definition')}
                                    >
                                        Charger une police
                                    </button>
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            )}
            <input
                ref={gridFontFileInput}
                type="file"
                accept=".ttf,.otf,.woff,.woff2"
                style={{ display: 'none' }}
                onChange={(e) => {
                    const file = e.target.files?.[0];
                    if (file) {
                        loadFontFile(file, 'grid');
                        e.target.value = '';
                    }
                }}
            />
            <input
                ref={setFileInput}
                type="file"
                accept=".json,.txt"
                style={{ display: 'none' }}
                onChange={(e) => {
                    const file = e.target.files?.[0];
                    handleSetFile(file);
                    e.target.value = '';
                }}
            />
            <input
                ref={definitionFontFileInput}
                type="file"
                accept=".ttf,.otf,.woff,.woff2"
                style={{ display: 'none' }}
                onChange={(e) => {
                    const file = e.target.files?.[0];
                    if (file) {
                        loadFontFile(file, 'definition');
                        e.target.value = '';
                    }
                }}
            />
        </div>
    );
};

// src/components/toolbar/Toolbar.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { themeChange } from 'theme-change';
    import type { AppearanceSettings, Grid } from '../../models/types';

    interface Props {
        onResize: (width: number, height: number) => void;
        currentGrid?: Grid;
        onInputFocus: (isFocused: boolean) => void;
        appearance: AppearanceSettings;
        onAppearanceChange: (changes: Partial<AppearanceSettings>) => void;
        onGridNameChange: (name: string) => void;
        onGridSetChange: (set: string) => void;
        saveStatus: 'empty' | 'saved' | 'modified';
        onSave: () => void;
        onNewGrid: () => void;
        onShowGrids: () => void;
        selectedDirection?: 'horizontal' | 'vertical';
        onDirectionToggle?: () => void;
        editMode: 'normal' | 'separator';
        onToggleEditMode: () => void;
        previewAppearance: boolean;
        onTogglePreviewAppearance: () => void;
        previewWithoutLetters: boolean;
        onTogglePreviewWithoutLetters: () => void;
        showSidebar: boolean;
        onToggleSidebar: () => void;
    }

    let {
        onResize,
        currentGrid,
        onInputFocus,
        appearance,
        onAppearanceChange,
        onGridNameChange,
        onGridSetChange,
        saveStatus,
        onSave,
        onNewGrid,
        onShowGrids,
        selectedDirection = 'horizontal',
        onDirectionToggle,
        editMode,
        onToggleEditMode,
        previewAppearance,
        onTogglePreviewAppearance,
        previewWithoutLetters,
        onTogglePreviewWithoutLetters,
        showSidebar,
        onToggleSidebar
    }: Props = $props();

    type ColorKey =
        | 'blackCellColor'
        | 'cellBackgroundColor'
        | 'arrowColor'
        | 'letterColor'
        | 'definitionTextColor'
        | 'borderColor'
        | 'separatorColor';

    let activePanel = $state<'info' | 'appearance' | null>(null);
    let dimensions = $state({
        width: currentGrid?.size.width || 15,
        height: currentGrid?.size.height || 15
    });
    let gridFontCustom = $state(appearance.gridFont);
    let definitionFontCustom = $state(appearance.definitionFont);
    let colorDrafts = $state<Record<ColorKey, string>>({
        blackCellColor: appearance.blackCellColor,
        cellBackgroundColor: appearance.cellBackgroundColor,
        arrowColor: appearance.arrowColor,
        letterColor: appearance.letterColor,
        definitionTextColor: appearance.definitionTextColor,
        borderColor: appearance.borderColor,
        separatorColor: appearance.separatorColor
    });

    let isDark = $state((localStorage.getItem('theme') || document.documentElement.getAttribute('data-theme')) === 'dark');

    let gridFontFileInput = $state<HTMLInputElement | null>(null);
    let definitionFontFileInput = $state<HTMLInputElement | null>(null);

    // theme-change gère le basculement de thème et le mémorise dans localStorage.
    onMount(() => themeChange(false));

    // Recopie la taille de la grille active dans les champs locaux.
    $effect(() => {
        dimensions = {
            width: currentGrid?.size.width || 15,
            height: currentGrid?.size.height || 15
        };
    });

    // Recopie l'apparence courante dans les brouillons éditables.
    $effect(() => {
        colorDrafts = {
            blackCellColor: appearance.blackCellColor,
            cellBackgroundColor: appearance.cellBackgroundColor,
            arrowColor: appearance.arrowColor,
            letterColor: appearance.letterColor,
            definitionTextColor: appearance.definitionTextColor,
            borderColor: appearance.borderColor,
            separatorColor: appearance.separatorColor
        };
        gridFontCustom = appearance.gridFont;
        definitionFontCustom = appearance.definitionFont;
    });

    const handleResize = () => {
        onResize(dimensions.width, dimensions.height);
        activePanel = null;
    };

    const colorFields: { key: ColorKey; label: string }[] = [
        { key: 'blackCellColor', label: 'Cases noires' },
        { key: 'cellBackgroundColor', label: 'Cases blanches' },
        { key: 'letterColor', label: 'Lettres (grille)' },
        { key: 'definitionTextColor', label: 'Définitions' },
        { key: 'borderColor', label: 'Bordures & flèches' },
        { key: 'separatorColor', label: 'Barre de séparation' }
    ];

    const fontOptions = [
        { label: 'Charger une police…', value: 'custom' },
        { label: 'Inter', value: "'Inter', 'Segoe UI', system-ui, sans-serif" },
        { label: 'Arial', value: "Arial, 'Helvetica Neue', sans-serif" },
        { label: 'Roboto', value: "'Roboto', 'Segoe UI', system-ui, sans-serif" },
        { label: 'Lato', value: "'Lato', 'Segoe UI', system-ui, sans-serif" },
        { label: 'Open Sans', value: "'Open Sans', 'Segoe UI', system-ui, sans-serif" },
        { label: 'Montserrat', value: "'Montserrat', 'Segoe UI', system-ui, sans-serif" },
        { label: 'Georgia', value: "Georgia, 'Times New Roman', serif" },
        { label: 'Courier New', value: "'Courier New', monospace" }
    ];

    const normalizeHex = (value: string): string | null => {
        const trimmed = value.trim();
        const short = trimmed.match(/^#([0-9a-fA-F]{3})$/);
        if (short) {
            const rgb = short[1];
            return `#${rgb[0]}${rgb[0]}${rgb[1]}${rgb[1]}${rgb[2]}${rgb[2]}`.toLowerCase();
        }
        if (/^#([0-9a-fA-F]{6})$/.test(trimmed)) return trimmed.toLowerCase();
        return null;
    };

    const isValidColor = (value: string) =>
        normalizeHex(value) !== null || /^rgb(a)?\(/i.test(value.trim()) || /^hsl(a)?\(/i.test(value.trim());

    const sanitizeColor = (value: string, fallback: string) => {
        const normalized = normalizeHex(value);
        if (normalized) return normalized;
        const trimmed = value.trim();
        if (isValidColor(trimmed)) return trimmed;
        return fallback;
    };

    const commitColor = (key: ColorKey, value: string) => {
        const sanitized = sanitizeColor(value, appearance[key]);
        colorDrafts = { ...colorDrafts, [key]: sanitized };
        if (sanitized !== appearance[key]) onAppearanceChange({ [key]: sanitized });
    };

    const resolveColorValue = (key: ColorKey) =>
        normalizeHex(colorDrafts[key]) ?? normalizeHex(appearance[key]) ?? '#000000';

    const applyFontChange = (key: 'gridFont' | 'definitionFont', value: string) => {
        const dataKey = key === 'gridFont' ? 'gridFontData' : 'definitionFontData';
        onAppearanceChange({ [key]: value.trim() || appearance[key], [dataKey]: undefined });
    };

    const selectedFontValue = (current: string) => {
        const match = fontOptions.find((opt) => opt.value === current);
        return match ? match.value : 'custom';
    };

    const loadFontFile = async (file: File, target: 'grid' | 'definition') => {
        try {
            const fontName = file.name.replace(/\.[^/.]+$/, '') || 'CustomFont';
            const fontData = await file.arrayBuffer();
            const fontFace = new FontFace(fontName, fontData);
            await fontFace.load();
            document.fonts.add(fontFace);

            const fontValue = `'${fontName}'`;
            const dataUrl = await new Promise<string>((resolve, reject) => {
                const reader = new FileReader();
                reader.onload = () => resolve(String(reader.result));
                reader.onerror = () => reject(reader.error);
                reader.readAsDataURL(file);
            });
            if (target === 'grid') {
                gridFontCustom = fontValue;
                onAppearanceChange({ gridFont: fontValue, gridFontData: dataUrl });
            } else {
                definitionFontCustom = fontValue;
                onAppearanceChange({ definitionFont: fontValue, definitionFontData: dataUrl });
            }
        } catch (error) {
            console.error('Erreur lors du chargement de la police :', error);
            window.alert('Impossible de charger cette police. Merci de réessayer.');
        }
    };

    const triggerFontUpload = (target: 'grid' | 'definition') => {
        (target === 'grid' ? gridFontFileInput : definitionFontFileInput)?.click();
    };

</script>

<div class="navbar min-h-14 gap-2 border-b border-base-300 bg-base-100 px-3">
    <div class="navbar-start gap-1">
        <button class="btn btn-sm btn-primary btn-square" onclick={onShowGrids} title="Toutes les grilles" aria-label="Grilles">
            <svg xmlns="http://www.w3.org/2000/svg" class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" />
            </svg>
        </button>
        <button class="btn btn-sm btn-ghost btn-square" onclick={onNewGrid} title="Nouvelle grille" aria-label="Nouvelle grille">
            <svg xmlns="http://www.w3.org/2000/svg" class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" />
            </svg>
        </button>
        <button class="btn btn-sm btn-ghost btn-square" onclick={() => (activePanel = 'info')} title="Infos de la grille" aria-label="Infos">
            <svg xmlns="http://www.w3.org/2000/svg" class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="12" cy="12" r="9" /><line x1="12" y1="11" x2="12" y2="16" /><line x1="12" y1="8" x2="12" y2="8" />
            </svg>
        </button>
        {#if onDirectionToggle}
            <button class="btn btn-sm btn-ghost btn-square" onclick={onDirectionToggle} title={`Direction : ${selectedDirection === 'horizontal' ? 'horizontale' : 'verticale'} (Tab)`} aria-label="Changer la direction">
                <span class="text-lg leading-none">{selectedDirection === 'horizontal' ? '→' : '↓'}</span>
            </button>
        {/if}
        <button
            class="btn btn-sm btn-square {editMode === 'separator' ? 'btn-secondary' : 'btn-ghost'}"
            onclick={onToggleEditMode}
            title="Mode séparateur : relier deux cases voisines par un trait pointillé"
            aria-label="Mode séparateur"
        >
            <svg xmlns="http://www.w3.org/2000/svg" class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <rect x="3" y="6" width="6" height="12" rx="1" /><rect x="15" y="6" width="6" height="12" rx="1" /><line x1="12" y1="3" x2="12" y2="21" stroke-dasharray="3 3" />
            </svg>
        </button>
    </div>

    <div class="navbar-center hidden lg:flex">
        <div class="flex gap-4 text-sm text-base-content/70">
            <span>Grille : <span class="font-medium text-base-content">{currentGrid?.name || 'Sans nom'}</span></span>
            {#if currentGrid?.set}
                <span>Set : <span class="font-medium text-base-content">{currentGrid.set}</span></span>
            {/if}
        </div>
    </div>

    <div class="navbar-end gap-1">
        {#snippet diskIcon()}
            <svg xmlns="http://www.w3.org/2000/svg" class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z" /><polyline points="17 21 17 13 7 13 7 21" /><polyline points="7 3 7 8 15 8" />
            </svg>
        {/snippet}
        {#if saveStatus === 'empty'}
            <span class="btn btn-sm btn-ghost btn-square btn-disabled" title="Grille vide">{@render diskIcon()}</span>
        {:else}
            <button
                class="btn btn-sm btn-ghost btn-square {saveStatus === 'modified' ? 'text-warning' : 'text-success'}"
                onclick={onSave}
                title={saveStatus === 'modified' ? 'Modifications non enregistrées — cliquez pour enregistrer' : 'Grille enregistrée'}
                aria-label="Enregistrer la grille"
            >
                {@render diskIcon()}
            </button>
        {/if}

        <button
            class="btn btn-sm btn-ghost btn-square"
            onclick={onToggleSidebar}
            title={showSidebar ? "Masquer le panneau 'Mots trouvés'" : "Afficher le panneau 'Mots trouvés'"}
            aria-label="Basculer le panneau des mots"
        >
            {#if showSidebar}
                <svg xmlns="http://www.w3.org/2000/svg" class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <rect x="3" y="4" width="18" height="16" rx="2" /><line x1="15" y1="4" x2="15" y2="20" />
                </svg>
            {:else}
                <svg xmlns="http://www.w3.org/2000/svg" class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <rect x="3" y="4" width="18" height="16" rx="2" />
                </svg>
            {/if}
        </button>

        <button
            class="btn btn-sm btn-square {previewAppearance ? 'btn-secondary' : 'btn-ghost'}"
            onclick={onTogglePreviewAppearance}
            title="Aperçu avec les couleurs d'export (rendu du PDF)"
            aria-label="Aperçu des couleurs d'export"
        >
            <svg xmlns="http://www.w3.org/2000/svg" class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7z" /><circle cx="12" cy="12" r="3" />
            </svg>
        </button>
        <button
            class="btn btn-sm btn-square {previewWithoutLetters ? 'btn-secondary' : 'btn-ghost'}"
            onclick={onTogglePreviewWithoutLetters}
            title="Aperçu sans lettres (comme puzzle vide)"
            aria-label="Aperçu sans lettres"
        >
            <svg xmlns="http://www.w3.org/2000/svg" class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <text x="12" y="17" text-anchor="middle" font-size="16" font-weight="bold" stroke-dasharray="2,2" stroke-width="1.5" fill="none">A</text>
            </svg>
        </button>
        <button class="btn btn-sm btn-ghost btn-square" onclick={() => (activePanel = 'appearance')} title="Apparence (export)" aria-label="Apparence">
            <svg xmlns="http://www.w3.org/2000/svg" class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="13.5" cy="6.5" r="1.5" fill="currentColor" stroke="none" /><circle cx="17.5" cy="10.5" r="1.5" fill="currentColor" stroke="none" /><circle cx="8.5" cy="7.5" r="1.5" fill="currentColor" stroke="none" /><circle cx="6.5" cy="12.5" r="1.5" fill="currentColor" stroke="none" /><path d="M12 2a10 10 0 0 0 0 20 2.5 2.5 0 0 0 2-4 2.5 2.5 0 0 1 2-4h1a5 5 0 0 0 5-5c0-4.5-4.5-7-10-7z" />
            </svg>
        </button>

        <label class="swap swap-rotate btn btn-sm btn-ghost btn-square" title="Basculer le thème clair / sombre">
            <input type="checkbox" data-toggle-theme="dark,light" bind:checked={isDark} aria-label="Mode sombre" />
            <svg class="swap-off size-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 3a1 1 0 0 1 1 1v1a1 1 0 1 1-2 0V4a1 1 0 0 1 1-1zm0 14a5 5 0 1 0 0-10 5 5 0 0 0 0 10zm0 1a1 1 0 0 1 1 1v1a1 1 0 1 1-2 0v-1a1 1 0 0 1 1-1zM4 12a1 1 0 0 1-1 1H2a1 1 0 1 1 0-2h1a1 1 0 0 1 1 1zm18 0a1 1 0 0 1-1 1h-1a1 1 0 1 1 0-2h1a1 1 0 0 1 1 1zM5.6 5.6a1 1 0 0 1 1.4 0l.7.7a1 1 0 1 1-1.4 1.4l-.7-.7a1 1 0 0 1 0-1.4zm11 11a1 1 0 0 1 1.4 0l.7.7a1 1 0 0 1-1.4 1.4l-.7-.7a1 1 0 0 1 0-1.4zm1.4-11a1 1 0 0 1 0 1.4l-.7.7a1 1 0 1 1-1.4-1.4l.7-.7a1 1 0 0 1 1.4 0zm-11 11a1 1 0 0 1 0 1.4l-.7.7a1 1 0 0 1-1.4-1.4l.7-.7a1 1 0 0 1 1.4 0z"/></svg>
            <svg class="swap-on size-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M21.5 14.1A8.5 8.5 0 0 1 9.9 2.5a1 1 0 0 0-1.3-1.3A10.5 10.5 0 1 0 22.8 15.4a1 1 0 0 0-1.3-1.3z"/></svg>
        </label>
    </div>
</div>

{#if activePanel === 'info'}
    <div class="modal modal-open">
        <div class="modal-box max-w-xl">
            <div class="flex items-center justify-between">
                <h3 class="text-lg font-bold">Infos</h3>
                <button class="btn btn-sm btn-circle btn-ghost" onclick={() => (activePanel = null)} aria-label="Fermer">✕</button>
            </div>

            <div class="mt-4 flex flex-col gap-3">
                <label class="flex flex-col gap-1 text-sm font-medium">
                    Nom
                    <input
                        type="text"
                        class="input input-sm w-full"
                        placeholder="Nom de la grille"
                        value={currentGrid?.name || ''}
                        oninput={(e) => onGridNameChange(e.currentTarget.value)}
                        onfocus={() => onInputFocus(true)}
                        onblur={() => onInputFocus(false)}
                    />
                </label>
                <label class="flex flex-col gap-1 text-sm font-medium">
                    Set
                    <input
                        type="text"
                        class="input input-sm w-full"
                        placeholder="Set (tag, ex: Août 2026)"
                        value={currentGrid?.set || ''}
                        oninput={(e) => onGridSetChange(e.currentTarget.value)}
                        onfocus={() => onInputFocus(true)}
                        onblur={() => onInputFocus(false)}
                    />
                </label>
                <div class="flex flex-col gap-1 text-sm font-medium">
                    Taille
                    <div class="join">
                        <input type="number" class="input input-sm join-item w-20" bind:value={dimensions.width} min="5" max="25" />
                        <span class="join-item flex items-center border border-base-300 bg-base-200 px-2">×</span>
                        <input type="number" class="input input-sm join-item w-20" bind:value={dimensions.height} min="5" max="25" />
                        <button class="btn btn-sm join-item" onclick={handleResize}>Appliquer</button>
                    </div>
                </div>
            </div>
        </div>
        <button type="button" class="modal-backdrop" onclick={() => (activePanel = null)} aria-label="Fermer"></button>
    </div>
{/if}

{#if activePanel === 'appearance'}
    <div class="modal modal-open">
        <div class="modal-box max-w-2xl">
            <div class="flex items-center justify-between">
                <h3 class="text-lg font-bold">Apparence</h3>
                <button class="btn btn-sm btn-circle btn-ghost" onclick={() => (activePanel = null)} aria-label="Fermer">✕</button>
            </div>

            <div class="mt-4 grid gap-4 sm:grid-cols-2">
                {#each colorFields as { key, label } (key)}
                    <label class="flex items-center justify-between gap-2 text-sm">
                        <span>{label}</span>
                        <span class="flex items-center gap-1">
                            <input
                                type="color"
                                class="h-8 w-10 rounded border border-base-300 bg-base-100"
                                value={resolveColorValue(key)}
                                oninput={(e) => commitColor(key, e.currentTarget.value)}
                                onfocus={() => onInputFocus(true)}
                                onblur={() => onInputFocus(false)}
                                aria-label={label}
                            />
                            <input
                                type="text"
                                class="input input-xs w-24"
                                bind:value={colorDrafts[key]}
                                onfocus={() => onInputFocus(true)}
                                onblur={() => {
                                    commitColor(key, colorDrafts[key]);
                                    onInputFocus(false);
                                }}
                                placeholder="#000000"
                            />
                        </span>
                    </label>
                {/each}

                <label class="flex items-center justify-between gap-2 text-sm">
                    <span>Épaisseur séparateurs</span>
                    <input
                        type="number"
                        class="input input-xs w-24"
                        min={0.25}
                        max={3}
                        step={0.25}
                        value={appearance.separatorWidth}
                        oninput={(e) => onAppearanceChange({ separatorWidth: Math.max(0.25, Math.min(3, Number(e.currentTarget.value) || 0.25)) })}
                        onfocus={() => onInputFocus(true)}
                        onblur={() => onInputFocus(false)}
                    />
                </label>

                <label class="flex flex-col gap-1 text-sm">
                    <span>Police de la grille</span>
                    <select
                        class="select select-sm w-full"
                        value={selectedFontValue(appearance.gridFont)}
                        onchange={(e) => {
                            const value = e.currentTarget.value;
                            if (value === 'custom') triggerFontUpload('grid');
                            else applyFontChange('gridFont', value);
                        }}
                        onfocus={() => onInputFocus(true)}
                        onblur={() => onInputFocus(false)}
                    >
                        {#each fontOptions as option (option.value)}
                            <option value={option.value}>{option.label}</option>
                        {/each}
                    </select>
                    {#if selectedFontValue(appearance.gridFont) === 'custom'}
                        <div class="join">
                            <input
                                type="text"
                                class="input input-xs join-item grow"
                                bind:value={gridFontCustom}
                                oninput={(e) => applyFontChange('gridFont', e.currentTarget.value)}
                                onfocus={() => onInputFocus(true)}
                                onblur={() => onInputFocus(false)}
                                placeholder="Ex: Inter, Arial"
                            />
                            <button type="button" class="btn btn-xs join-item" onclick={() => triggerFontUpload('grid')}>Charger</button>
                        </div>
                    {/if}
                </label>

                <label class="flex flex-col gap-1 text-sm">
                    <span>Police des définitions</span>
                    <select
                        class="select select-sm w-full"
                        value={selectedFontValue(appearance.definitionFont)}
                        onchange={(e) => {
                            const value = e.currentTarget.value;
                            if (value === 'custom') triggerFontUpload('definition');
                            else applyFontChange('definitionFont', value);
                        }}
                        onfocus={() => onInputFocus(true)}
                        onblur={() => onInputFocus(false)}
                    >
                        {#each fontOptions as option (option.value)}
                            <option value={option.value}>{option.label}</option>
                        {/each}
                    </select>
                    {#if selectedFontValue(appearance.definitionFont) === 'custom'}
                        <div class="join">
                            <input
                                type="text"
                                class="input input-xs join-item grow"
                                bind:value={definitionFontCustom}
                                oninput={(e) => applyFontChange('definitionFont', e.currentTarget.value)}
                                onfocus={() => onInputFocus(true)}
                                onblur={() => onInputFocus(false)}
                                placeholder="Ex: Inter, Georgia"
                            />
                            <button type="button" class="btn btn-xs join-item" onclick={() => triggerFontUpload('definition')}>Charger</button>
                        </div>
                    {/if}
                </label>
            </div>
        </div>
        <button type="button" class="modal-backdrop" onclick={() => (activePanel = null)} aria-label="Fermer"></button>
    </div>
{/if}

<input
    bind:this={gridFontFileInput}
    type="file"
    accept=".ttf,.otf,.woff,.woff2"
    class="hidden"
    onchange={(e) => {
        const file = e.currentTarget.files?.[0];
        if (file) {
            loadFontFile(file, 'grid');
            e.currentTarget.value = '';
        }
    }}
/>
<input
    bind:this={definitionFontFileInput}
    type="file"
    accept=".ttf,.otf,.woff,.woff2"
    class="hidden"
    onchange={(e) => {
        const file = e.currentTarget.files?.[0];
        if (file) {
            loadFontFile(file, 'definition');
            e.currentTarget.value = '';
        }
    }}
/>
